#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# PodMonitor for Producer pods (if ServiceMonitor doesn't work)
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fluss-producer-pods
  namespace: fluss
  labels:
    app: fluss-producer
spec:
  selector:
    matchLabels:
      app: fluss-producer
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
# PodMonitor for Flink JobManager pods
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flink-jobmanager-pods
  namespace: fluss
  labels:
    app: flink
    component: jobmanager
spec:
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
# PodMonitor for Flink TaskManager pods
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flink-taskmanager-pods
  namespace: fluss
  labels:
    app: flink
    component: taskmanager
spec:
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s

